<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/DL_Bonus_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron using sklearn

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
iris = load_iris(as_frame=True)
X = iris.data
y = iris.target

y_binary = np.where(y == 0, 0, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size = 0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

perceptron = Perceptron(max_iter=300, eta0 = 0.1, random_state=42)
perceptron.fit(X_train, y_train)

y_pred_train = perceptron.predict(X_train)
acc_train = accuracy_score(y_train, y_pred_train)

print(acc_train)

y_pred_test = perceptron.predict(X_test)
acc_test = accuracy_score(y_test, y_pred_test)

print(acc_test)

1.0
1.0


# Perceptron from scratch

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd

In [ ]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3)*1e-4
    print(f'Initial weights before training: \n {self.weights}')

    self.eta = eta
    self.epoch = epochs

  def activation_func(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0, 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y
    X_with_bias = np.c_[self.X, -np.ones((len(X), 1))]
    print(f'X with bias: \n {X_with_bias}')

    for epoch in range(self.epoch):
      print(f'Epoch no: {epoch}')

      y_hat = self.activation_func(X_with_bias, self.weights)

      error = self.y - y_hat
      print(f'Error: {error}')

      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f'Updated weights: \n {self.weights}')

  def predict(self, X):
    X_with_bias = np.c_[self.X, -np.ones((len(X), 1))]
    return self.activation_func(X_with_bias, self.weights)

# AND Operation

In [ ]:
data = {
    'x1': [0, 0, 1, 1],
    'x2': [0, 1, 0, 1],
    'y': [0, 0, 0, 1]
}

AND = pd.DataFrame(data)

X = AND.drop('y', axis = 1)
y = AND['y']

model = Perceptron(eta = 0.1, epochs= 10)
model.fit(X, y)

Initial weights before training: 
 [-6.93654534e-06  7.10454600e-05 -7.08679370e-05]
X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch no: 0
Error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
 [-0.10000694 -0.09992895  0.29992913]
Epoch no: 1
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
 [-6.93654534e-06  7.10454600e-05  1.99929132e-01]
Epoch no: 2
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
 [0.09999306 0.10007105 0.09992913]
Epoch no: 3
Error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
 [-6.93654534e-06  7.10454600e-05  2.99929132e-01]
Epoch no: 4
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
 [0.09999306 0.10007105 0.19992913]
Epoch no: 5
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [0.09999306 0.10007105 0.19992913]
Epoch no: 6
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64

In [ ]:
model.predict(X)

array([0, 0, 0, 1])

In [ ]:
model.weights

array([0.09999306, 0.10007105, 0.19992913])

In [17]:
data = {
    'x1': [0, 0, 1, 1],
    'x2': [0, 1, 0, 1],
    'y': [0, 1, 1, 1]
}

OR = pd.DataFrame(data)

X = OR.drop('y', axis = 1)
y = OR['y']

model_Or = Perceptron(eta = 0.1, epochs= 10)
model_Or.fit(X, y)

Initial weights before training: 
 [4.38745401e-05 1.15966364e-04 7.73641039e-05]
X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch no: 0
Error: 0    0
1    0
2    1
3    0
Name: y, dtype: int64
Updated weights: 
 [ 0.10004387  0.00011597 -0.09992264]
Epoch no: 1
Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [1.00043875e-01 1.15966364e-04 7.73641039e-05]
Epoch no: 2
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [1.00043875e-01 1.15966364e-04 7.73641039e-05]
Epoch no: 3
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [1.00043875e-01 1.15966364e-04 7.73641039e-05]
Epoch no: 4
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [1.00043875e-01 1.15966364e-04 7.73641039e-05]
Epoch no: 5
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
 [1.00043875e-01 1.15966364e-04 7.73641039e-05]
Epoch no: 6
Error: 0    0
1    0
2    0
3

In [21]:
array = model_Or.predict(X)
array

array([0, 1, 1, 1])