<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_09_Extra_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Problem 01

In [12]:
one = np.array([1,2,3])

one_dim = np.ndim(one)
one_shape = np.shape(one)
# print(one_dim)
# print(one_shape)

two = np.array([
    [1,2,3],
    [4,5,6]
    ])

two_dim = np.ndim(two)
two_shape = np.shape(two)
# print(two_dim)
# print(two_shape)


three = np.array([
    [[1,2,3],
    [4,5,6]],
    [[7, 8, 9],
     [10, 11, 12]]
])

three_dim = np.ndim(three)
three_shape = np.shape(three)
# print(three_dim)
# print(three_shape)

3
(2, 2, 3)


# Problem 02

In [16]:
zero = np.zeros((3, 3))
print(zero)

One = np.ones((2, 5))
print(One)

seven = np.full((3, 3), 7)
print(seven)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Problem 03

In [25]:
arr = np.arange(10, 50, 2)
print(arr)

# Using linspace
arr_line = np.linspace(10, 48, 20)
print(arr_line)

# Using range with list comprehension
arr_loop = np.array([x for x in range(10, 50, 2)])
print(arr_loop)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48.]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


# Problem 04

In [39]:
random_arr = np.random.randint(0, 15, size = (4,4))

print(random_arr)

first_row = random_arr[:1]
print("first row :",first_row)

last_col = random_arr[:,3]
print("last col :",last_col)

sub_arr = random_arr[1:3, 1:3]
print("Sub array :", sub_arr)

[[ 5  6  5  4]
 [10 11  5 14]
 [10  0  7 13]
 [ 9  7  8  6]]
first row : [[5 6 5 4]]
last col : [ 4 14 13  6]
Sub array : [[11  5]
 [ 0  7]]
